/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }
    
    private void kosongkan_formSaran(){
        
        txtNamabagiansaran.setEditable(true);
        txtNamabagiansaran.setText(null);
        txtIdSaran.setText(null);
        txtSaran.setText(null);
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        btnLaptop = new javax.swing.JButton();
        btnSaran = new javax.swing.JButton();
        btnInformasi = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnKembali = new javax.swing.JToggleButton();
        IsiMenu = new javax.swing.JPanel();
        isiHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        IsiLaptop = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        IsiInformasi = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        IsiSaran = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        txtNamabagiansaran = new javax.swing.JTextField();
        txtSaran = new javax.swing.JTextField();
        btnSimpanSaran = new javax.swing.JButton();
        btnTambahSaran = new javax.swing.JButton();
        jLabel68 = new javax.swing.JLabel();
        txtIdSaran = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");

        Menu.setBackground(new java.awt.Color(255, 153, 0));

        btnLaptop.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLaptop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-laptop-20.png"))); // NOI18N
        btnLaptop.setText("Beli Laptop");
        btnLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaptopActionPerformed(evt);
            }
        });

        btnSaran.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-talk-20.png"))); // NOI18N
        btnSaran.setText("Berikan Saran");
        btnSaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaranActionPerformed(evt);
            }
        });

        btnInformasi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnInformasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-profiles-20.png"))); // NOI18N
        btnInformasi.setText("Informasi Kami");
        btnInformasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformasiActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 0, 0));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-shutdown-30.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-home-20.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnKembali.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLaptop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInformasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSaran, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnInformasi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        IsiMenu.setBackground(new java.awt.Color(255, 255, 255));
        IsiMenu.setLayout(new java.awt.CardLayout());

        isiHome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Hallo, Selamat datang di Aplikasi Penjualan Laptop");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Kami menyediakan penjualan Laptop dengan jenis tipe yang tersedia,");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Laptop yang kami jual tentu sangat mendukung aktifitas anda seperti :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Untuk keperluan kerja kantoran, Editing film / Music dan Gaming.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Kami menawarkan berbagai macam laptop dengan harga yang bervariasi.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Semua Laptop mendapatkan Garansi resmi 2 tahun");

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FotoLaptop/Asus-ROG-Zephyrus-S-GX701.jpg"))); // NOI18N

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel40.setText("Ingat kami juga menjual Laptop Original dan dalam keadaan Baru");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel41.setText("Kelebihan jika membeli Laptop Di tempat kami :");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel42.setText("1. Setiap Laptop akan mendapatkan Sistem Operasi (OS) terbaru dan Original !");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel43.setText("2. Setiap Laptop mendapatkan 1 buah paket tambahan berupa Mouse, Headset dan Joy Stick / Xbox 360 Controller");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel44.setText("3. Mendapatkan Garansi 2 Tahun !");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel45.setText("4. Mendapatkan Voucher Game : DOTA, Mobile Legends, Black Desert Mobile ");

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel46.setText("5. Jika barang dalam keadaan rusak boleh dikembalikan dan uang anda akan kembali");

        javax.swing.GroupLayout isiHomeLayout = new javax.swing.GroupLayout(isiHome);
        isiHome.setLayout(isiHomeLayout);
        isiHomeLayout.setHorizontalGroup(
            isiHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiHomeLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(isiHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(isiHomeLayout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(isiHomeLayout.createSequentialGroup()
                        .addGroup(isiHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addComponent(jLabel44)
                            .addComponent(jLabel43)
                            .addComponent(jLabel42)
                            .addComponent(jLabel41)
                            .addComponent(jLabel40)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, isiHomeLayout.createSequentialGroup()
                .addContainerGap(364, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel39)
                .addGap(182, 182, 182))
            .addGroup(isiHomeLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        isiHomeLayout.setVerticalGroup(
            isiHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiHomeLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel46)
                .addGroup(isiHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(isiHomeLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel6))
                    .addGroup(isiHomeLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel39)))
                .addContainerGap(1776, Short.MAX_VALUE))
        );

        IsiMenu.add(isiHome, "card2");

        IsiLaptop.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Lenovo Legion Y7000");

        jLabel8.setText("Intel Core i7-9750H");

        jLabel10.setText("NVIDIA GeForce GTX 1660Ti");

        jLabel11.setText("8 GB DDR4 & 1 TB HDD + 256 GB SSD ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Rp. 13.090.000");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-buy-20.png"))); // NOI18N
        jButton6.setText("Beli");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FotoLaptop/Asus-ZenBook-Pro-Duo.jpg"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Asus ZenBook Pro Duo i7");

        jLabel15.setText("Intel Core i7-9750H 2.6GHz New");

        jLabel16.setText("NVIDIA GeForce RTX 2060");

        jLabel17.setText("32 GB 2666MHz DDR 4 & 1 TB New");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Rp. 44.199.000");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-buy-20.png"))); // NOI18N
        jButton7.setText("Beli");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FotoLaptop/Dell-XPS-15-7590-UHD-4K-Ci7-9750H.jpg"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Dell XPS 15 7590 UHD 4K i7 9750H");

        jLabel21.setText("9th Generation Intel Core i7-9750H");

        jLabel22.setText("NVIDIA GeForce GTX 1650 4 GB DDR5");

        jLabel23.setText("16 GB DDR4 & 512 GB");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Rp. 25.950.000");

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-buy-20.png"))); // NOI18N
        jButton8.setText("Beli");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FotoLaptop/Omen-by-HP-15.jpg"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Omen by HP 15");

        jLabel27.setText("Intel Core i7-9750H 2.6 GHz");

        jLabel28.setText("NVIDIA GeForce RTX 2060 Graphics");

        jLabel29.setText("16 GB DDR4 & 512 GB");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Rp. 15.999.000");

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-buy-20.png"))); // NOI18N
        jButton9.setText("Beli");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FotoLaptop/Asus-ROG-Zephyrus-S-GX701.jpg"))); // NOI18N

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setText("HABIS");

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FotoLaptop/Lenovo-ThinkPad-X1-Extreme.jpg"))); // NOI18N

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setText("Lenovo ThinkPad X1 Extreme i7");

        jLabel35.setText("Intel Core i7-8750H");

        jLabel36.setText("NVIDIA GeForce GTX 1050Ti");

        jLabel37.setText("32 GB DDR4 & 1 TB SSD");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setText("Rp. 21.999.000");

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-buy-20.png"))); // NOI18N
        jButton10.setText("Beli");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FotoLaptop/Lenovo-Legion-Y7000-32ID-i7-9750H.jpg"))); // NOI18N

        javax.swing.GroupLayout IsiLaptopLayout = new javax.swing.GroupLayout(IsiLaptop);
        IsiLaptop.setLayout(IsiLaptopLayout);
        IsiLaptopLayout.setHorizontalGroup(
            IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IsiLaptopLayout.createSequentialGroup()
                .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IsiLaptopLayout.createSequentialGroup()
                        .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IsiLaptopLayout.createSequentialGroup()
                                    .addGap(145, 145, 145)
                                    .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addGroup(IsiLaptopLayout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jButton6)))
                                    .addGap(67, 67, 67))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IsiLaptopLayout.createSequentialGroup()
                                    .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(IsiLaptopLayout.createSequentialGroup()
                                            .addGap(127, 127, 127)
                                            .addComponent(jLabel10))
                                        .addGroup(IsiLaptopLayout.createSequentialGroup()
                                            .addGap(148, 148, 148)
                                            .addComponent(jLabel8)))
                                    .addGap(47, 47, 47))
                                .addGroup(IsiLaptopLayout.createSequentialGroup()
                                    .addGap(148, 148, 148)
                                    .addComponent(jLabel9)))
                            .addGroup(IsiLaptopLayout.createSequentialGroup()
                                .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(IsiLaptopLayout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addGroup(IsiLaptopLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel22)
                                                    .addComponent(jLabel21)))))
                                    .addGroup(IsiLaptopLayout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(jLabel7))
                                    .addGroup(IsiLaptopLayout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(3, 3, 3)))
                        .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IsiLaptopLayout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(IsiLaptopLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel34))
                                    .addGroup(IsiLaptopLayout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabel35))
                                    .addGroup(IsiLaptopLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel36)
                                            .addGroup(IsiLaptopLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel37)
                                                    .addGroup(IsiLaptopLayout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(IsiLaptopLayout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jButton10))
                                                            .addComponent(jLabel38)))))))
                                    .addComponent(jLabel31)))
                            .addGroup(IsiLaptopLayout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(jLabel32))))
                    .addGroup(IsiLaptopLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton8)
                                .addComponent(jLabel24)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IsiLaptopLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(121, 121, 121))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IsiLaptopLayout.createSequentialGroup()
                                .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel29)
                                    .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(IsiLaptopLayout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jButton9))
                                        .addComponent(jLabel30)))
                                .addGap(138, 138, 138))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IsiLaptopLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(139, 139, 139))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IsiLaptopLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(98, 98, 98)))
                        .addGroup(IsiLaptopLayout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabel28)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IsiLaptopLayout.createSequentialGroup()
                        .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IsiLaptopLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton7))
                            .addComponent(jLabel18))
                        .addGap(143, 143, 143))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IsiLaptopLayout.createSequentialGroup()
                .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(IsiLaptopLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, IsiLaptopLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IsiLaptopLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15))))
                            .addGroup(IsiLaptopLayout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(IsiLaptopLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(104, 104, 104))
        );
        IsiLaptopLayout.setVerticalGroup(
            IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IsiLaptopLayout.createSequentialGroup()
                .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IsiLaptopLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IsiLaptopLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))
                            .addGroup(IsiLaptopLayout.createSequentialGroup()
                                .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(IsiLaptopLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15))
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7))))
                    .addGroup(IsiLaptopLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addGap(82, 82, 82)
                .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IsiLaptopLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel34)
                                .addComponent(jLabel26))
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(IsiLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8)
                            .addComponent(jButton10)))
                    .addGroup(IsiLaptopLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)))
                .addContainerGap(1680, Short.MAX_VALUE))
        );

        IsiMenu.add(IsiLaptop, "card3");

        IsiInformasi.setBackground(new java.awt.Color(255, 255, 255));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FotoInfo/Ismi.jpg"))); // NOI18N

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FotoInfo/Bagus.jpg"))); // NOI18N

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FotoInfo/Ringgo.JPG"))); // NOI18N

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel51.setText("Ismi Zahra Rezkatiana");

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel52.setText("118140011");

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel53.setText("Institut Teknologi Sumatera");

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel54.setText("Jl. Kasmawari Gg. Sakum");

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel55.setText("Bagus Dwi Prasetyo");

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel56.setText("118140070");

        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel57.setText("Institut Teknologi Sumatera");

        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel58.setText("Jl. Sultan Agung Gg. Tirtayasa");

        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel59.setText("Ringgo Galih Sadewo");

        jLabel60.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel60.setText("118140076");

        jLabel63.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel63.setText("Institut Teknologi Sumatera");

        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel64.setText("Jl. Cendana IV");

        javax.swing.GroupLayout IsiInformasiLayout = new javax.swing.GroupLayout(IsiInformasi);
        IsiInformasi.setLayout(IsiInformasiLayout);
        IsiInformasiLayout.setHorizontalGroup(
            IsiInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IsiInformasiLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel48)
                .addGap(191, 191, 191)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel50)
                .addGap(118, 118, 118))
            .addGroup(IsiInformasiLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(IsiInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel53)
                    .addGroup(IsiInformasiLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel54)))
                .addGroup(IsiInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IsiInformasiLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel57))
                    .addGroup(IsiInformasiLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel58)))
                .addGroup(IsiInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IsiInformasiLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addGroup(IsiInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IsiInformasiLayout.createSequentialGroup()
                                .addComponent(jLabel61)
                                .addGap(171, 171, 171))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IsiInformasiLayout.createSequentialGroup()
                                .addComponent(jLabel63)
                                .addGap(75, 75, 75))))
                    .addGroup(IsiInformasiLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel64)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(IsiInformasiLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel51)
                .addGap(159, 159, 159)
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel59)
                .addGap(104, 104, 104))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IsiInformasiLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jLabel52)
                .addGap(233, 233, 233)
                .addComponent(jLabel56)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(IsiInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IsiInformasiLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel62))
                    .addComponent(jLabel60))
                .addGap(145, 145, 145))
        );
        IsiInformasiLayout.setVerticalGroup(
            IsiInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IsiInformasiLayout.createSequentialGroup()
                .addGroup(IsiInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IsiInformasiLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(IsiInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel50)
                            .addComponent(jLabel49)
                            .addComponent(jLabel48))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(IsiInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51)
                            .addComponent(jLabel55)
                            .addComponent(jLabel59))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(IsiInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel56)
                            .addComponent(jLabel52)
                            .addComponent(jLabel60)))
                    .addGroup(IsiInformasiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel61))
                    .addGroup(IsiInformasiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel62)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IsiInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IsiInformasiLayout.createSequentialGroup()
                        .addGroup(IsiInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel53)
                            .addComponent(jLabel57))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(IsiInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel54)
                            .addComponent(jLabel58)))
                    .addGroup(IsiInformasiLayout.createSequentialGroup()
                        .addComponent(jLabel63)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel64)))
                .addContainerGap(1869, Short.MAX_VALUE))
        );

        IsiMenu.add(IsiInformasi, "card5");

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel65.setText("Masukan saran dan nama anda");

        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel66.setText("Nama :");

        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel67.setText("Saran anda :");

        txtNamabagiansaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamabagiansaranActionPerformed(evt);
            }
        });

        txtSaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaranActionPerformed(evt);
            }
        });

        btnSimpanSaran.setBackground(new java.awt.Color(0, 255, 0));
        btnSimpanSaran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSimpanSaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-upload-document-30.png"))); // NOI18N
        btnSimpanSaran.setText("Simpan");
        btnSimpanSaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanSaranActionPerformed(evt);
            }
        });

        btnTambahSaran.setBackground(new java.awt.Color(0, 255, 0));
        btnTambahSaran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTambahSaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-add-file-30.png"))); // NOI18N
        btnTambahSaran.setText("Tambah Saran");
        btnTambahSaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahSaranActionPerformed(evt);
            }
        });

        jLabel68.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel68.setText("Id_Pembeli :");

        javax.swing.GroupLayout IsiSaranLayout = new javax.swing.GroupLayout(IsiSaran);
        IsiSaran.setLayout(IsiSaranLayout);
        IsiSaranLayout.setHorizontalGroup(
            IsiSaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IsiSaranLayout.createSequentialGroup()
                .addGroup(IsiSaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IsiSaranLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(IsiSaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel67)
                            .addComponent(jLabel66)
                            .addComponent(jLabel68))
                        .addGap(18, 18, 18)
                        .addGroup(IsiSaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IsiSaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSaran, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IsiSaranLayout.createSequentialGroup()
                                    .addComponent(btnTambahSaran)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSimpanSaran, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(IsiSaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtIdSaran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                .addComponent(txtNamabagiansaran, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(IsiSaranLayout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jLabel65)))
                .addContainerGap(393, Short.MAX_VALUE))
        );
        IsiSaranLayout.setVerticalGroup(
            IsiSaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IsiSaranLayout.createSequentialGroup()
                .addGroup(IsiSaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IsiSaranLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel65))
                    .addGroup(IsiSaranLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(IsiSaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel66)
                            .addComponent(txtNamabagiansaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(IsiSaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(txtIdSaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(IsiSaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaran, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel67))
                .addGap(18, 18, 18)
                .addGroup(IsiSaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpanSaran)
                    .addComponent(btnTambahSaran))
                .addContainerGap(1821, Short.MAX_VALUE))
        );

        IsiMenu.add(IsiSaran, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IsiMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IsiMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaptopActionPerformed
        // TODO add your handling code here:
        
        //Menghapus
        IsiMenu.removeAll();
        IsiMenu.repaint();
        IsiMenu.revalidate();
        
        //Menampilkan isi Home
        IsiMenu.add(IsiLaptop);
        IsiMenu.repaint();
        IsiMenu.revalidate();
        
    }//GEN-LAST:event_btnLaptopActionPerformed

    private void btnInformasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformasiActionPerformed
        // TODO add your handling code here:
        
        //Menghapus
        IsiMenu.removeAll();
        IsiMenu.repaint();
        IsiMenu.revalidate();
        
        //Menampilkan isi Home
        IsiMenu.add(IsiInformasi);
        IsiMenu.repaint();
        IsiMenu.revalidate();
        
    }//GEN-LAST:event_btnInformasiActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Terima kasih sudah menggunakan Aplikasi kami :) ");
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        
        //Menghapus
        IsiMenu.removeAll();
        IsiMenu.repaint();
        IsiMenu.revalidate();
        
        //Menampilkan isi Home
        IsiMenu.add(isiHome);
        IsiMenu.repaint();
        IsiMenu.revalidate();
        
    }//GEN-LAST:event_btnHomeActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtNamabagiansaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamabagiansaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamabagiansaranActionPerformed

    private void txtSaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaranActionPerformed

    private void btnSimpanSaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanSaranActionPerformed
        // TODO add your handling code here:
        
        try {

            String sql = "INSERT INTO Saran VALUES ('"+txtIdSaran.getText()+"','"+txtNamabagiansaran.getText()+"','"+ txtSaran.getText()+"')";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil..:");
            
            

        }
        catch (HeadlessException | SQLException e){
            
            JOptionPane.showMessageDialog(null, "Mohon maaf Id_Produk yang anda masukan tidak terdaftar di Database kami, harap masukan ulang !");
        }
    }//GEN-LAST:event_btnSimpanSaranActionPerformed

    private void btnSaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaranActionPerformed
        // TODO add your handling code here:
        
         //Menghapus
        IsiMenu.removeAll();
        IsiMenu.repaint();
        IsiMenu.revalidate();
        
        //Menampilkan isi Home
        IsiMenu.add(IsiSaran);
        IsiMenu.repaint();
        IsiMenu.revalidate();
    }//GEN-LAST:event_btnSaranActionPerformed

    private void btnTambahSaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahSaranActionPerformed
        // TODO add your handling code here:
        
        //mengosongkan form saran
        kosongkan_formSaran();
        txtNamabagiansaran.setFocusable(true);
    }//GEN-LAST:event_btnTambahSaranActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        
        this.dispose(); // mengeluarkan tampilan
        
        TampilanAwal tampilanawal = new TampilanAwal ();
        tampilanawal.setVisible(true);
        
        
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IsiInformasi;
    private javax.swing.JPanel IsiLaptop;
    private javax.swing.JPanel IsiMenu;
    private javax.swing.JPanel IsiSaran;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInformasi;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JToggleButton btnKembali;
    private javax.swing.JButton btnLaptop;
    private javax.swing.JButton btnSaran;
    private javax.swing.JButton btnSimpanSaran;
    private javax.swing.JButton btnTambahSaran;
    private javax.swing.JPanel isiHome;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtIdSaran;
    private javax.swing.JTextField txtNamabagiansaran;
    private javax.swing.JTextField txtSaran;
    // End of variables declaration//GEN-END:variables

    private void tampilkan_data() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
